### ISSUE TITLE
GridFS getting started

### ISSUE THREAD

**Issue by cgarciae** [vadimtsushko/mongo_dart#61]
Hi,

I was wondering if you can give me an example on how to use GridFS in Mongo Dart? I was storing files on the hardrive directly but I just learned about GridFS, however I didn't find anything about it on the examples.

Thanks!

**Comment by vadimtsushko** [comment]
There are tests for GridFS. Look at https://github.com/vadimtsushko/mongo_dart/blob/master/test/gridfs_tests.dart#L137
