### ISSUE TITLE
Getting the `_id` of a newly inserted object

### ISSUE THREAD

**Issue by cgarciae** [vadimtsushko/mongo_dart#62]
Currently I create an `ObjectId` during insert so I can send back to the client the `id` of the new object.

```
var id = new ObjectId();
...insert ({'_id : id, ...})...
```

My worry is that maybe creating the id like this does not guaranty uniqueness at least within a collection. If I don't specify the `_id` myself, how can I access it after insert?

**Comment by vadimtsushko** [comment]
I believe using pre-created id's is pretty safe. ObjectId constructor is bit identical with mongo-db but (i hope) is similiar by features. Look at https://github.com/vadimtsushko/bson/blob/master/lib/src/types/objectid.dart#L29

**Comment by cgarciae** [comment]
Thanks!
