### ISSUE TITLE
Sort and limit API

### ISSUE THREAD

**Issue by cgarciae** [vadimtsushko/mongo_dart#66]
I need to write code like this
```js
//pure mongo
db.foo.find().sort({_id:1}).limit(50);
```
but find the the API for Dart makes me write code like this
```dart
db.collection ("foo").find(where.sortBy('_id'))..limit = 5;
```
There is no actual sort method on `Cursor` so you have to include it in the `ModifierBuilder` and limit turns out to be a field, which looks odd from a user perspective. 

For the sorting issue, if the implementation of a `Cursor sort (String fieldName, {bool descending: false})` is too involved then its ok.

On the other hand, `limit` could be turned into a function easily but it would be a breaking change. Cascade operators `..` let you chain operations, but the rest of the API uses normal `.` access to methods that tend to be chainable, mixing both styles if you want to do everything in a single line is confusing.

**Comment by vadimtsushko** [comment]
>> I need to write code like this
>> //pure mongo
>>    db.foo.find().sort({_id:1}).limit(50);

`Selector` parameter of `find` method can express all that. Limit, skip, field projection. With it you can write code like this:

    db.foo.find(where.sortBy('_id').limit(50));

See example in tests:

    Future testLimitWithSortByAndSkip(){
      Db db = new Db('${DefaultUri}mongo_dart-test','testLimitWithSortByAndSkip');
      int counter = 0;
      Cursor cursor;
      return db.open().then((c){
        DbCollection coll = db.collection('testLimit');
        coll.remove();
        for(int n=0;n<600;n++){
          coll.insert({"a":n});
        }
        cursor = coll.find(where.sortBy('a').skip(300).limit(10));
        return cursor.forEach((e)=>counter++);
      }).then((v){
        expect(counter,10);
        expect(cursor.state,State.CLOSED);
        expect(cursor.cursorId,0);
        return db.close();
      });
    }

**Comment by cgarciae** [comment]
Thanks @vadimtsushko ! Looks much better. 

I want to contribute with some documentation but I don't feel I know Mongo well enough. I'll create something basic but it would help if you create a skeleton and the community can complete it.

**Comment by vadimtsushko** [comment]
I'm sorry for neglecting wiki and documentation in general. 
I currently have very little time for anything beyond my actual work.
I you will manage to put something on wiki I'll try to revise it and edit if necessary as soon as possible.
