### ISSUE TITLE
Deprecated system collections in Mongodb 3.0

### ISSUE THREAD

**Issue by Scorpiion** [vadimtsushko/mongo_dart#67]
Hi @vadimtsushko,

I noticed when I tried to use db.listCollections() on a Mongodb 3.0.2 database that it did not work. After looking into the driver code and looking over Mongodb documentation I found that the system collections; ["<database>.system.namespaces"](http://docs.mongodb.org/manual/reference/system-collections/#<database>.system.namespaces) and ["<database>.system.indexes"](http://docs.mongodb.org/manual/reference/system-collections/#<database>.system.indexes), that are used by this driver, both are now deprecated since version 3.0.

I tried to implement a fix for listCollections() but did not quite succeed. I manged to write code that executed the new command ["db.getCollectionInfos()"](http://docs.mongodb.org/manual/reference/method/db.getCollectionInfos/#db.getCollectionInfos): 

```dart
  Future<List> listCollections2() {
    return executeDbCommand(DbCommand.createQueryAdminCommand({"listCollections":1})).then((val) {

      print(val.runtimeType);
      print(val);

      return new Future.value([]);
    });
  }
```

It prints this:
```dart
_CompactLinkedHashMap
{cursor: {id: 0, ns: admin.$cmd.listCollections, firstBatch: []}, ok: 1.0}
```

I don't know exactly how to proceed with that information. However, there is new command called ["db.getCollectionInfos()"](http://docs.mongodb.org/manual/reference/method/db.getCollectionInfos/#db.getCollectionInfos) that seems to be exactly what's needed to implement "db.listCollections()". But for some reason I can't get that command to work. I tried to implement it like this:

```dart
  static DbCommand createGetCollectionInfosCommand(Db db) {
    return new DbCommand(db, SYSTEM_COMMAND_COLLECTION, MongoQueryMessage.OPTS_NO_CURSOR_TIMEOUT, 0, -1, {'getCollectionInfos':1}, null);
  }
```

I figured that since both "dropDatabase" and "getCollectionInfos" are listed on the same [docs page (the list to the left)](http://docs.mongodb.org/manual/reference/method/db.getCollectionInfos/#db.getCollectionInfos) that they should work similarly. But the output I get is only this:

```
Unhandled exception:
Uncaught Error: {ok: 0.0, errmsg: no such command: getCollectionInfos, code: 59, bad cmd: {getCollectionInfos: 1}}
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)
```

Could it be that there is some update to the underlying protocol used or am I just missing some detail?

I know you don't have too much time to work on mongo_dart at the moment, but if you could help out a little bit or point me in the right direction it would be very much appreciated.

Regards, Robert

**Comment by vadimtsushko** [comment]
Hi Robert.
I've downloaded current mongodb version (3.0.2) and tried to run tests and samples on it.
With shame I've found that  I do not have test for db.listCollections() but it present in example\queries.dart
And for me it works with fresh mongodb version. 
I have that line as last line in output for example\queries.dart

    List of collections: [new_collecion, new_collecion_to_remove, testLimit, students, simple_data, testCount, testDistinct, testSaveWithIntegerId, testSaveWithObjectId, testSkip, testDates, testupdateWithUpsert, testupdateWitMultiUpdate, new_big_collection1, testNextObjectToEnd, new_big_collection, new_big_collection2, testcol, testAggregate]

So apparently system.namespaces functionality deprecated but not removet from mongodb yet. 
For db.indexInformation I have test testIndexInformation() and it works too.

Please check output of example\queries.dart on your system.

Anyway we must do something with deprecated things and I think your initial hit with executeDbCommand(DbCommand.createQueryAdminCommand({"listCollections":1})) is pertinant one. getCollectionInfos is a simple wrapper as I see in documentation so I believe MongoDB do not have system command for it.

Apparently listCollections returns some info from which we should create Cursor, at the time I can not see example for such a thing in codebase. It should be easy or not so easy - I can not say from the top of my head. I'll try to look at it as soon as I have some time.

**Comment by Scorpiion** [comment]
Hi @vadimtsushko, 

Thanks for you reply, I forgot to mention that I use WiredTiger. Could you try to add this to the startup command of Mongodb to test with WiredTiger:

```
  --storageEngine wiredTiger
```

**Comment by Scorpiion** [comment]
Yes, I think system.namespaces is still part of the old storage engine, but will be disabled or removed later. For new deployments the [benefits are many of WiredTiger](http://www.mongodb.com/blog/post/whats-new-mongodb-30-part-3-performance-efficiency-gains-new-storage-architecture) as I'm sure you know. I think that might be the main reason that system.namespaces is deprecated, in favor of WiredTiger. 

I see, that would explain why I could not get getCollectionInfos to work, if it's only a wrapper and not a real system command. The output I posted above is the name of the cursor:

```
{cursor: {id: 0, ns: admin.$cmd.listCollections, firstBatch: []}, ok: 1.0}
```

I just not sure how to use it.

**Comment by Scorpiion** [comment]
The output of example\queries.dart:

```
[skipped the first parts...]

{_id: ObjectId("55376e187c9bf6293a4134f9"), my_field: 535, str_field: str_535}
{_id: ObjectId("55376e187c9bf6293a41355d"), my_field: 635, str_field: str_635}
Count of records with my_field > 995: 4
List of databases: []
List of collections: []
```

Mongod command:
```
mongod --storageEngine wiredTiger --dbpath /croot/mongodb/data --noauth 
```

Mongod version:
```
db version v3.0.2
git version: 6201872043ecbbc0a4cc169b5482dcf385fc464f
OpenSSL version: OpenSSL 1.0.1f 6 Jan 2014
```

**Comment by vadimtsushko** [comment]
Thank you, I've started mongo with WiredTiger and now 3 of my test are broken :)
And I've even found that I have one collectionInfo related test: testCollectionInfoCursor
It is one from a set of broken tests.

> For new deployments the benefits are many of WiredTiger as I'm sure you know. I think that might be the main reason that system.namespaces is deprecated, in favor of WiredTiger

Actually I have not known a thing about WiredTiger. I myself very far from mongodb, web programming and dart in my work (well, at a momemt I sometimes use dart on server side). Mongo_dart was started as purely educational project. You know the argument - you have to learn something new just to keep yourself warm (why not dart - Gilad is fascinating person), and best way to learn something is to make with it something useful (so my try with mongodb).

Anyway I'l try to fix that as soon as possible.

**Comment by Scorpiion** [comment]
Okay, I understand. I visited the [Inqlik.ru](http://Inqlik.ru) homepage, from your Linkedin page, and assumed that you used Mongodb somehow at work. I work at a startup company called [DartVoid](http://www.dartvoid.com/), we do Dart hosting with Mongodb databases. We will release some big updates to our platform very soon and after that I would love to help out a little bit more with this driver. 

WiredTiger, is Mongodb's new storage engine, it was developed by a different company that Mongodb bought at the end of last year. The reason the newest Mongodb version is called 3.X and not 2.X is simply because of all the benefits that WiredTiger brings. This infographic show the benefits of Mongodb 3, you only get the write performance and compression if you use WiredTiger:

![infographic for Mongodb 3](http://s3.amazonaws.com/info-mongodb-com/FINAL%20-%203.0Launch-Infographic-v7-1.jpg)

Creating a Mongodb driver for Dart was indeed an impressive educational project I must say. It would be very nice if you could fix so the tests work again. I don't have time to try solving it myself right now, but I would be happy to review or double check your fixes if you like. I will look at them either way. 

Thanks for your quick reply.

**Comment by vadimtsushko** [comment]
Hi Robert.
I've just pushed v0.1.47-dev to github. It has new methods getCollectionNames and getCollectionInfos from MongoDB v3 API. Current example in example\query.dart

Version is not ready to publish yet. Old functions must be deprecated, new functions must be made backward compatible, tests must be changed/added and so on. But new functions work for me on WiredTiger, so maybe you may look at this version.

**Comment by Scorpiion** [comment]
Hi Vadim,

That sounds great, I'm happy to hear that. 

I just downloaded the latest development version and the test works for me now. I tested first with the old code again and then updated and checked with the new version. Now I get this output:

Before:
```
Count of records with my_field > 995: 4
List of databases: []
List of collections: []
```

After:
```
Count of records with my_field > 995: 4
List of databases: [mate_logs, local, mongo_dart-test]
List of collections (MongoDB v2 API: [simple_data]
List of collections (MongoDB v3 API: [simple_data, system.indexes]
List of collections (MongoDB v3 API: [{name: simple_data, options: {}}, {name: system.indexes, options: {}}]
```

I also looked at the code, it looks good I think. I have some things to prepare before going to the Dart Summit on Monday, but I will do some more tests next week.

**Comment by vadimtsushko** [comment]
Good.
I wonder what was wrong with `List of databases: []` part though. That api was not changed in any way.
Theoretically it should work with all versions of mongodb on old and new versions of mongo_dart.
Anyway. Glad it works for you.

**Comment by Scorpiion** [comment]
Hi again,

I'm sorry that was an error on my end, I was running towards the wrong database instance. Here are correct before and after output:

Before:
```
Count of records with my_field > 995: 4
List of databases: [local, mongo_dart-test, my_db]
List of collections: []
```

After:
```
Count of records with my_field > 995: 4
List of databases: [local, mongo_dart-test, my_db]
List of collections (MongoDB v2 API: []
List of collections (MongoDB v3 API: [simple_data]
List of collections (MongoDB v3 API: [{name: simple_data, options: {}}]
```

**Comment by vadimtsushko** [comment]
Now that is expected output.

**Comment by Scorpiion** [comment]
Yes, indeed.

Come think about it, you have missed the ending ")" on the outputs on row 65, 68 and 71:

Example of row 65:
```
print('List of collections (MongoDB v2 API: $collections');
```
-->
```
print('List of collections (MongoDB v2 API: $collections)');
```

**Comment by vadimtsushko** [comment]
Yes, I should fix it. But actually by analogue with other drivers I better should deprecate old api and make new (v3.0) API backward compatible with mongodb v 2. So example and tests should be rewritten anyway.

**Comment by Scorpiion** [comment]
You I understand, sounds like a good plan.

**Comment by vadimtsushko** [comment]
And by the way - have a nice Dart Summit, Robert :)

**Comment by Scorpiion** [comment]
Thank you very much, I hope you get the time to watch some of the presentations on the livestream or later on Youtube as well. :)

**Comment by vadimtsushko** [comment]
Definitely, I watch dart evolution closely even though I do not involved in it deeply enough. It is fascinating how quickly technology developes and matures
.

**Comment by Scorpiion** [comment]
:+1:

**Comment by Scorpiion** [comment]
I believe we can close this one now as 0.1.47 has been released.

**Comment by Scorpiion** [comment]
Or are there any more deprecated system collections that should be fixed?

**Comment by vadimtsushko** [comment]
Hi Robert.
I believe at the moment all coding is done. 
New db.getCollectionNames(), db.getCollectionInfos(), collection.getIndexes() methods are now backward compatible with earlier versions of MongoDb.
collectionsInfoCursor, listCollections, indexInformation methods of Db deprecated.
Feel free to reopen it if something does not work for you

**Comment by Scorpiion** [comment]
Sounds great, thanks!
