### ISSUE TITLE
Parse ObjectID

### ISSUE THREAD

**Issue by zijam** [vadimtsushko/mongo_dart#68]
When I try to parse the ObjectID from MongoDB in a web client, I get the following error  
```
Invalid argument(s): Expected hexadecimal string with length of 24, got ObjectId("55a90733833d91c457d78065")
```
My code is 
```
import 'package:bson/bson.dart';

ObjectId _id;
factory Customer.fromJson(Map m){
  var c =  new Customer()
  ...
  ...
  c._id = ObjectId.parse(m["_id"]);
}
```

**Comment by vadimtsushko** [comment]
Apparently m["_id"] already has valid ObjectID. If m created by bson, that would be case.
So maybe you should change your code to:

    ...
    c._id = m["_id"];

**Comment by zijam** [comment]
I forgot to show the class that calls on 'Customer.fromJson'
```
_http
      .get('http://localhost:8080/api/customers/get')
      .then((response) {
        var list = response.data.map((e) => new Customer.fromJson(e));
        completer.complete(list);
      });
```
I'm using Angulardart and Shelf.

I have attached an example of the request to the server. 
![screen shot 2015-07-24 at 22 35 32](https://cloud.githubusercontent.com/assets/695088/8884108/5e2e547a-3254-11e5-9f40-e4fd17319a61.png)
 and the code is
```
Future<Response> saveCustomers(Request request) {
  var maps, cus = [];
  return _auth.open().then((_) {
      return request.readAsString().then((v) {
        maps = JSON.decode(v);
        maps.forEach((m1) {
          print('saving: ${m1.toString()}');

          customerColl
            .findOne(where.id(m1['_id']))
            ...
            ...
```
In the image ObjectID is a string and I need to convert it to an ObjectID object, when I try to use 'where.id(m1['_id'])', it gives me an error.
```
type 'String' is not a subtype of type 'ObjectId' of 'value'.
```

**Comment by vadimtsushko** [comment]
Well, I think now I know what is going on. My first guess is plainly wrong - would you pass real ObjectId into ObjectId.parse method there would be all sorts of type errors.
I suppose on server side you do not do special toJson encoding of Customer.
Currently in that case ObjectId is saved in Json as result of toString method - therefore that ObjectId('123fa....') representation. 
You could ensurre that ObjectId is saved simply as hexString while encoding MongoDb object to Json
For example:

        _toEncodable(obj) {
      if (obj is DateTime) {
        return obj.toString();
      }
      if (obj is ObjectId) {
        return obj.toHexString();
      }
      return obj.toJson();
    }
    String jsObj = JSON.encode(obj, toEncodable: _toEncodable);

(I've added DateTime encoding for good measure - date fields stored in MongoDb shout require something like it too)

**Comment by vadimtsushko** [comment]
But looking at your scenario (I suppose it is quite usual) - I see that current behaviour of ObjectId is not so smart. It has toXml() method defaulting to toString() - so encoding to JSon silently stores ObjectId in form not suitable for ObjectId.parse().
Maybe right thing would be to do same as DateTime. It do not have toJson() method so it force you to make encoding manually,

On the other hand it could make toJson return toHexString() so it silently by default store in json value convenient for decoding by ObjectId.parse

I'll probably switch to last option in next version of bson and mongo_dart.

**Comment by zijam** [comment]
I think the last option it best, since 
```
Json.encode()
```
automatically calls toJson method on objects.

My workaround solution is currently calling this method on server and client side, when I need to create my object. 
```
String objecid(String id) {
  return id.substring(10, 34);
}
```

**Comment by vadimtsushko** [comment]
Have any of your objects `DateTime` properties? I think `toJson()` without `toEncodable` parameter breaks on map with DateTime value

**Comment by zijam** [comment]
No they don't have any DataTime properties

**Comment by zijam** [comment]
When I query the database, the returned *_id* is a string
```
 return customers.find(where.exists('_id').sortBy('name')).forEach((Map c){
      cus.add(JSON.encode(c, toEncodable: _toEncodable));
    });
```
![screen shot 2015-07-25 at 13 21 17](https://cloud.githubusercontent.com/assets/695088/8889188/17bb9b52-32d0-11e5-8945-1bed36a8da39.png)

All the other value has been converted to their correct types.
Wouldn't it be better if *_id* was converted to a ObjectId by the mongodart driver?

**Comment by vadimtsushko** [comment]
I've updated mongo_dart package at the github with that behaviour. Have not published that version at pub yet. Can you check how it would work for you?

**Comment by zijam** [comment]
If it is the master branch, then I can only see that you have modified yaml and a test file.

I have work around the problem, by using these method
```
JSON.decode(v, reviver: _toDecodable)
JSON.encode(m, toEncodable: _toEncodable)

 dynamic _toDecodable(k, v) {

  if ('_id' == k)
    return ObjectId.parse(v);

  return v;
}

dynamic _toEncodable(obj) {

  if (obj is ObjectId) {
    return obj.toHexString();
  }

  return obj.toJson();
}
```

The ObjectId get converted to Hex string, when sending between server and client and vice versa.

**Comment by vadimtsushko** [comment]
>> If it is the master branch, then I can only see that you have modified yaml and a test file.

Yes, I've modified yaml file and now it use new version of bson package. In that version ObjectId.toJson implemented as `toHexString` instead of `toString`.

Your workaround should work with any version of mongo_dart though.

**Comment by zijam** [comment]
Bson code on GitHub still shows ```toJson```  to use ```toString```.
But the code from pub.dartlang.org use ```toHexString```
It works fine now.

**Comment by vadimtsushko** [comment]
Good catch. I have published bson on put but not pushed it on github.
Thank you for pointing me at that
