### ISSUE TITLE
Cursor count

### ISSUE THREAD

**Issue by zijam** [vadimtsushko/mongo_dart#69]
How do you get count of element from Cursor, when using it with **find** method.
I would like to save some data objects to mongodb, but need to check if it already exists and update a variable on the object, before saving it back to mongodb. Some time the object doesn't exists and when I call 
```
cursor.nextObject().then((v) {
   print(v)
}) 
```
It doesn't call the *then* method of the future.

**Comment by vadimtsushko** [comment]
I not fully undestand what  you are trying to do. But almost certainly you shouldn't use cursor directly.
You can use `toList` or `forEach` to get result from `find` method.
There is also a `count` method that take same parameter as `find`

Take a look at [examples](https://github.com/vadimtsushko/mongo_dart/tree/master/example) for proper usage (I've just updated all examples to async/await features BTW)

For `count` https://github.com/vadimtsushko/mongo_dart/blob/master/example/queries.dart#L67

**Comment by zijam** [comment]
Thx.
It works better with async and await :+1:
