### ISSUE TITLE
add projection argument to DbCollection find method

### ISSUE THREAD

**Issue by thumbert** [vadimtsushko/mongo_dart#70]
Hi, 
The current Mongo find command accepts two arguments, 
db.collection.find(query, projection)

It is convenient to have the projection argument to limit the amount of data you return from the query. 
Can you consider adding it to the mongo_dart package?

Thanks, 
Tony

**Comment by vadimtsushko** [comment]
You can do projection now by `fields` and `excludeFields` methods of `SelectorBuilder`.
For example 

    db.products.find( { qty: { $gt: 25 } }, { item: 1, qty: 1 } )

in mongo_dart should look somewhat like:

    productsCollection.find(where.gt('qty',25).fields(['item','qty']))

Also look at: https://github.com/vadimtsushko/mongo_dart/blob/master/example/queries.dart#L22

**Comment by thumbert** [comment]
Thank you.  Actually, now that you pointed it out, I remember using it previously but then forgetting about how to do it. 

Great package!

**Comment by xavierhainaux** [comment]
The `fields` method takes a `List<String>` and cover the simple cases. 
But what about the more complex cases like `$elemMatch` and `$slice`?

https://docs.mongodb.com/manual/reference/operator/projection/elemMatch/
https://docs.mongodb.com/manual/reference/operator/projection/slice/

Having a second optional Map argument on `find` would unlock those operations.
