### ISSUE TITLE
Logger allocates lot of strings

### ISSUE THREAD

**Issue by rajmaniar** [vadimtsushko/mongo_dart#71]
All instances of the logger are using: logger.fine("Message $interpolation")
This allocates a lot of string that are then discarded by the logger (since our production logs are set to warning).

If that was changed to  logger.fine(()=>"Message $interpolation"), gc pressure would be reduced and actually is a noticeable improvement in our application.

**Comment by vadimtsushko** [comment]
Thank you for pointing me at that. I've made recommended changes - currently at github. 
Would be available in next pub release.

**Comment by rajmaniar** [comment]
Great! Thanks!

**Comment by vadimtsushko** [comment]
Just uploaded on pub version with this fix
