### ISSUE TITLE
Implement SCRAM-SHA-1 (default for MongoDb up from 3.0) authentication scheme

### ISSUE THREAD

**Issue by vadimtsushko** [vadimtsushko/mongo_dart#75]
Currenty users cannot authenticate in MongoDb 3.0 unless they make  changes in mongodb configuration (as described in https://jira.mongodb.org/browse/SERVER-17459 for example).
From end-user point of view that is bug

**Comment by Scorpiion** [comment]
Just a note, as this issue is related to #72 (related as in both are auth related), it might be beneficial to look at them at the same time.

**Comment by rightisleft** [comment]
This just cropped up when mongolab - one of the premier free tier mongo hosts - force upgraded everyone to 3.0

**Comment by Scorpiion** [comment]
@Pacane is working on this in a branch here: https://github.com/Pacane/mongo_dart/tree/scram-sha1

It's not done yet but in the works, if you have the time to help out feel free to jump in. It is a port of the C# mongo drivers implementation of SCRAM-SHA-1, but @Pacane is the one who knows most details. The latest talks about it was here (scroll down a little bit to Pacane's message):

https://dartlang.slack.com/archives/public-discuss/p1444998881002639

**Comment by rightisleft** [comment]
Great to hear that its being worked on. Is there an ETA on the fix? Working on a book that uses mongo_dart && mongolab with v3.0. Curious if i should include a work around or wait for the fix.

**Comment by Scorpiion** [comment]
Hi @rightisleft, fun to hear your working on a Dart book.

I would not say there is any specific ETA, with that said I think and hope it will be resolved quite soon, but hard to say. Pacane is using Mongolab as well (I don't) and that's his motivation to start working on this I think.

If you should include a work around or not depends on your own time schedule, if the book should be done next week, then it might be the best to do so. If it's months into the future, I would wait for a fix, but that's your decision to make.

**Comment by rightisleft** [comment]
The workaround listed doesnt actually work on mongolab as there is no admin access for free tier accounts. 

This ends up blocking many users who dont have admin level access to their databases.

**Comment by vadimtsushko** [comment]
I've done some minor corrections in Pacane's module, it seems to me that made it work (authentication work for me both with local mongodb 3.0 database and mongolab instance)
Hope it help Pacane in his efforts.

**Comment by vadimtsushko** [comment]
Robert, Jack: I think current dev version of mongo_dar (only on github now) now ready for internal testing. SCRAM auhtentication is imlemented. Changes are bacward compatible if authMechanism do not set as query option default auth schema selected on base of database version (SCRAM for 3.X)
AuthSource option added by the way too. 
@Pacane did great job implementing the stuff and continue to work with test and refactorings.

**Comment by rightisleft** [comment]
That's great news. I'll take a look shortly.

**Comment by Scorpiion** [comment]
This is indeed great news, I am going to testing it out now (SCRAM + authSource). :+1:

**Comment by Scorpiion** [comment]
Hi again, I could not find any issues, worked good for me.

**Comment by Pacane** [comment]
This was released in a beta version. Please reopen new issues concerning this.

**Comment by rightisleft** [comment]
My initial testing looked good against my unit tests - i have yet to migrate my app code
